title: Katie Hammer
logo: "/images/IMG_1256.jpg?raw=true" 
description: >
  My name is Katie Hammer and I am a rising senior at NC State studying computer science, 
  with a strong interest in data science. I am looking to grow my experience in the field 
  and share what I have to offer!
  <br>
  <a href="https://www.linkedin.com/in/kahammer/">LinkedIn Profile</a>
  </br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

