title: Katie Hammer
logo: "/images/Headshot.jpeg?raw=true" 
description: >
  My name is Katie Hammer and I'm a recent Computer Science graduate from NC State.
  I'm seeking an entry-level role in tech, with interests in data science,
  systems analytics, product management, and adjacent fields where I can grow and make an impact.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

