title: Katie Hammer
logo: "/images/IMG_1256.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Katie Hammer and I am a rising senior at NC State studying computer science, 
with a strong interest in data science. I am looking to grow my experience in the field 
and share what I have to offer!
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/kahammer/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
